# Generated by Django 4.2.6 on 2023-11-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sneakers',
            new_name='SneakersPair',
        ),
    ]
